[package]
name = "wordnet-morphy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
wordnet-types = { path = "../wordnet-types" }

[dev-dependencies]
wordnet-db = { path = "../wordnet-db" }
