name: Release Cargo

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_HOME: ${{ github.workspace }}/.cargo
  CARGO_TARGET_DIR: ${{ github.workspace }}/target
  WORDNET_DIR: ${{ github.workspace }}/open_english_wordnet_2024/oewn2024

jobs:
  check_tag:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry
            ${{ env.CARGO_HOME }}/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
          save-always: true
      - run: cargo fetch --locked
      - run: cargo run -p xtask -- check-tag --tag ${{ replace(github.event.workflow_run.ref, 'refs/tags/', '') }}

  publish:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: check_tag
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/registry
            ${{ env.CARGO_HOME }}/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
          save-always: true
      - run: cargo fetch --locked
      - run: cargo run -p xtask -- publish --tag ${{ replace(github.event.workflow_run.ref, 'refs/tags/', '') }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
